### ISSUE TITLE
SelfRegistration: pre-populated form data from URL parameters does not get saved to form on submit.

### ISSUE THREAD

**Issue by aaronhunt230** [SalesforceLabs/Configurable-Self-Registration-for-Experience-Cloud#34]
When I pre-populate from data in the url, it appears in the input field of the form on page load. Upon submission it throws an error that the field is missing which is also confirmed in the Error logging.

Error Log:
`An error occurred whilst trying to validate the password:Incomplete password information. Login name, New Password and Confirm Password must be provided.
Form Inputs: {Email=, Username=, confirmPassword=HIDDEN, password=HIDDEN}`

Form input:
![image](https://github.com/SalesforceLabs/Configurable-Self-Registration-for-Experience-Cloud/assets/57643885/16175ca3-af99-4a7d-96d6-0f2ac83be823)

Html input:  https://<my_Experience_Site>/Portal/login/SelfRegister?Email=selfRegTest@mailinator.com

Also to confirm, if I go back into the form and manually enter the email or other fields, it does work correctly and shows up on the form data in the logs. Have been able to successfully complete registration this way. 

Happy to provide any additional feedback that may be useful!

**Comment by jloweSFDC** [comment]
Thanks @aaronhunt230 - I'll take a look over at this over the next few days to understand whats happening and get back to you ASAP.

**Comment by jloweSFDC** [comment]
@aaronhunt230 - I believe I have fixed this. I can make v1.7 available on the AppExchange but it would be great if you could install it and use it against some of your use cases to make sure it works as intended. Reach out via email if you'd like a direct install link?

**Comment by aaronhunt230** [comment]
Hey Jamie, sorry I missed your last update. Awesome to hear it's been
resolved. I will have to download the latest and try it out.

**Comment by jamielowe1990** [comment]
Hey Aaron,

Haven’t got round to putting this on the app exchange yet as the internal system wasn't working last week when I closed this down. I'll try again tomorrow. Look for v1.7 on the listing if you get there before I do, otherwise you might pick up the wrong version.

Thanks,
Jamie

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jloweSFDC** [comment]
Aaron - just confirming the app exchange has now been updated to v1.7!

Jamie Lowe
Solution Architect | Salesforce
Mobile: 07393782908
<http://www.salesforce.com>
Please Note *Upcoming Absence: *
20th-28th July
14th-29th September

**Comment by willashe** [comment]
Hi @jloweSFDC this seems to be working great now for the custom self-registration link, but I'm wondering if it's possible to pass a query param from the URL directly into the username field of the custom login form?

**Comment by jamielowe1990** [comment]
Hi Will - I'm currently working on some changes to the login component. I'm planning to move the login form configuration to custom metadata so that it works in the same way as the self-registration form. Pre-populating the form with values from the URL is one the things it will gain by doing this in the same way. I don't have a confirmed timescale just yet as I need to properly test but it will be available hopefully over the next few weeks.

Thanks,
Jamie



Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by willashe** [comment]
Hi Jamie,
Great, thank you for the update and for your work on this package!
