### ISSUE TITLE
custom query new 255 character limit?

### ISSUE THREAD

**Issue by Mike-Cleaver-LB** [SalesforceLabs/Configurable-Self-Registration-for-Experience-Cloud#47]
After updating the component properly  (as per the quip) I tried to reinsert my matching query and got the error that it is longer than 255 characters. This query hasn't changed but now is not valid. Was there a change to the inputs here as I didn't think the length mattered? or was the query breaking before?

**Comment by jlowe-SFDC** [comment]
@Mike-Cleaver-LB - looks like this is an issue with the new Custom Property Editors. The property panel uses the "lightning__textType". Snippet from the development docs here:

![image](https://github.com/user-attachments/assets/acd0a22a-fcca-4b02-9186-6229a5bcda1f)

It seems a limit is enforced by the product with CPE's whereas there was no limit before with the standard property editor. The 255 character limit you are experiencing is more than the docs indicate though. I'll need to see if I can revert this back to a standard editor but it'll take some time and will likely need to release a bug fixed version.

**Comment by jlowe-SFDC** [comment]
Update...

I tested this further with trying to add back in a standard property and confirmed that the length is not enforced for these. However, doing it this way the standard property editor sits outside of the custom one, it doesn't appear in the correct "Base Settings" tab so the UI looks weird.

Therefore, I implemented a simple LWC (customPropertyEditorQuery) to show a simple lightning-input field that does not enforce any limit. I've updated the Custom Property Editor to reference this in place of the built in "lightning__textType" property type. This is then applied to the Base Settings tab to show in the correct place. Whilst more complex approach, it does work around the 255 character limit.

Finally, as per the developer guide PDF, Custom Property Editors are still in Beta. There are limitations in that a Custom Property Editor can't be updated, or deleted if they are referenced in LWCs so removing the customQuery property and replacing with the above configuration isn't possible during an upgrade. The package must be uninstalled and reinstalled with a new version to implement this fix.

Reference:
https://resources.docs.salesforce.com/rel1/doc/en-us/static/pdf/Custom_Property_Types_and_Editors_Beta_Summer-23.pdf

I'll package this up tomorrow, and give you an install link for testing.

**Comment by Mike-Cleaver-LB** [comment]
Thanks heaps! Would an alternative solution have been to use metadata/custom settings so that all the configurations are in a similar place? But you have a work around, that's awesome. Thanks for your work!

**Comment by jlowe-SFDC** [comment]
@Mike-Cleaver-LB I did consider that in the original version, but it would have meant another query to realise settings, whereas the property panel settings are just available in the LWC framework and reactive to changes automatically. The only reason the log setting is in a metadata record is so that you don't have to publish/re-publish the whole site in a production environment for an admin to turn it on/off. The settings on the component are generally set when you install and changes need to go through a release process to change the functionality. The fields naturally belong in custom metadata due to the 1:N nature. Hope that makes sense?

**Comment by Mike-Cleaver-LB** [comment]
Totally. Thanks for clarifying

**Comment by Mike-Cleaver-LB** [comment]
![image](https://github.com/user-attachments/assets/116a5a85-b2c0-40ba-b424-a3db8f916e78)
![image](https://github.com/user-attachments/assets/3e26226c-e19d-4164-8300-d6acf145c5cf)


Uninstalled, then installed 1.87, put the component on the page and saw "A custom query is required to use this component"
so i put my query in and still saw an error icon. No message this time, but after the 255th character it appears and the query doesn't save.

**Comment by jlowe-SFDC** [comment]
Sorry about this.

I've changed the type to a multi-line text. Its becoming a bit messy with not being able to remove old version of property editors (live and learn to not use beta features!). The code is in a new branch if you want to see whats changed. Unfortunately, I've had to rename the component (again) just to change the field type so you see @deprecated components installed as well and selectable in the Exp Builder. One day, I might need to repackage this and use 2GP and change the namespace to remove all the old non-working stuff.

Install link here as a beta version: 
[https://login.salesforce.com/packaging/installPackage.apexp?p0=04tWU00000049nt](javascript:srcUp('https%3A%2F%2Flogin.salesforce.com%2Fpackaging%2FinstallPackage.apexp%3Fp0%3D04tWU00000049nt%26isdtp%3Dp1');)

Can you test and come back to me? I'd like to get this issue closed down for you. If it works, I'll promote to major release and update AppExchange.

**Comment by Mike-Cleaver-LB** [comment]
no longer getting that error, but the date mapping seems to have reverted? this was a clean install

`There was a problem executing the specific query in the Custom Query property. Query used: SELECT id FROM Account WHERE (firstname = :firstName AND lastname = :lastName AND personemail = :email) or (firstname = :firstName AND lastname = :lastName AND PersonMobilePhone = :MobilePhone) or (firstname = :firstName AND personemail = :email AND PersonMobilePhone = :MobilePhone) or (lastname = :lastName AND personemail = :email AND PersonMobilePhone = :MobilePhone) or (firstname = :firstName AND lastname = :lastName and PersonBirthdate = :Birthday__c) or (firstname = :firstName AND personemail = :email and PersonBirthdate = :Birthday__c) or (firstname = :firstName AND PersonMobilePhone = :MobilePhone and PersonBirthdate = :Birthday__c) or (lastname = :lastName AND personemail = :email and PersonBirthdate = :Birthday__c) or (lastname = :lastName AND personemail = :email and PersonBirthdate = :Birthday__c) or (personemail = :email AND PersonMobilePhone = :MobilePhone and PersonBirthdate = :Birthday__c). Error: Invalid bind expression type of String for column of type Date`

![image](https://github.com/user-attachments/assets/ea60f57b-ff23-425e-ba6f-d195369a2d78)

**Comment by Mike-Cleaver-LB** [comment]
This error is only in the matching, storing the dates works perfectly. I think this is actually fine for now. IMO matching on birthday is a bad idea
https://en.wikipedia.org/wiki/Birthday_problem

maybe you promote this version and we worry about date matching another day? I think I can sway this with the client even in the intermediary, they want the data more than the matching

**Comment by jlowe-SFDC** [comment]
Hi @Mike-Cleaver-LB - done some more testing on this... the problem is actually the field name you've used as the metadata configuration. I think I can reproduce this, in my test org "Birthday__c" didn't exist as a field on my PersonAcount. When it parses the form fields, this then gets ignored because it doesn't exist so it doesn't know what the target type is and continues to just treat it as a string.

The fix is simple, update the metadata Field API Name to "PersonBirthdate" to match the field name you're matching against. Update your query to the below which uses "PersonBirthdate" not "Birthday__c" and the component converts the datatype as designed:

SELECT id FROM Account WHERE (firstname = :firstName AND lastname = :lastName AND personemail = :email) or (firstname = :firstName AND lastname = :lastName AND PersonMobilePhone = :MobilePhone) or (firstname = :firstName AND personemail = :email AND PersonMobilePhone = :MobilePhone) or (lastname = :lastName AND personemail = :email AND PersonMobilePhone = :MobilePhone) or (firstname = :firstName AND lastname = :lastName and PersonBirthdate = :PersonBirthdate) or (firstname = :firstName AND personemail = :email and PersonBirthdate = :PersonBirthdate) or (firstname = :firstName AND PersonMobilePhone = :MobilePhone and PersonBirthdate = :PersonBirthdate) or (lastname = :lastName AND personemail = :email and PersonBirthdate = :PersonBirthdate) or (lastname = :lastName AND personemail = :email and PersonBirthdate = :PersonBirthdate) or (personemail = :email AND PersonMobilePhone = :MobilePhone and PersonBirthdate = :PersonBirthdate)

**Comment by Mike-Cleaver-LB** [comment]
We are also storing the birthday on the user, do i also then need to api-name that field personbirthdate? it's currently birthday__c

**Comment by jlowe-SFDC** [comment]
Can I ask why this is on the user? Does it drive another process?

The self registration will match against the Account based on your current query so the field should be PersonBirthdate in the configuration and thus the bind variable :PersonBirthdate needs to be the same as described. If you need it on the user too, then I'd use a formula field to store it on the user, drilling through the related Contact field.

<img width="1165" alt="image" src="https://github.com/user-attachments/assets/e1a199b9-98e2-4f07-bda5-5f008a2e02f6">

<img width="481" alt="image" src="https://github.com/user-attachments/assets/c5af0a14-6e3f-495b-96b2-e65271ec9c41">

**Comment by Mike-Cleaver-LB** [comment]
We allow portal users to manage their own details. By default "My Profile" is the user object, and our client maintains and uses the person account, so these two need to be in sync, but also be independently maintainable. But as I said, we don't need matching on DOB for now. and just storing the data works for us with the beta build
